name: build and deploy api on local env
on:
  push:
    paths:
      - 'api/*'  # API コードの push のみをトリガー
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.9'
          architecture: x64
      - name: install python dependencies
        run:
          python -m pip install --upgrade pip
          pip install tqdm
          pip install Pillow
          pip install requests
      - name: run api with docker compose
        run:
          docker-compose -f api/docker-compose.yml up -d
      - name: run request
        run:
          cd api
          python request.py --host 0.0.0.0 --port 5000 --request_value 1 --debug
